[package]
name = "horton"
version = "0.0.1"
authors = ["horton <horton@trunk.io>"]
license = "MIT"
description = "trunk custom issue finder"
readme = "README.md"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.4"
regex = "1.6.0"
serde = {version = "1.0.145" , features = ["derive"]}
serde_json = "1.0.85"