[package]
name = "horton"
version = "0.0.1"
authors = ["horton <horton@trunk.io>"]
license = "MIT"
description = "trunk custom issue finder"
readme = "README.md"
edition = "2021"

[lib]
name = "horton"
path = "src/lib.rs"

[dependencies]
clap = {version = "4.0.8", features = ["derive"] }
regex = "1.6.0"
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.85"

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 3
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
debug = true
incremental = true

[profile.dev]
opt-level = 0
debug = true
incremental = true