# Configuration for trunk toolbox. Generate default by calling 'trunk-toolbox genconfig'

[ifchange]
enabled = false

[donotland]
enabled = true

[todo]
enabled = true
sleep_for = 2000

[neveredit]
enabled = false
paths = []

# nothing here
