# Configuration for trunk toolbox. Generate default by calling 'trunk-toolbox genconfig'

[ifchange]
enabled = false

[donotland]
enabled = true

[todo]
enabled = true

[neveredit]
enabled = false
paths = []
