# Configuration for trunk toolbox. Generate default by calling 'trunk-toolbox genconfig'

[ifchange]
enabled = true

[donotland]
enabled = true

[todo]
enabled = true

[neveredit]
enabled = true
paths = ["src/rules/mod.rs"] # paths to protect from modification
