# Configuration for trunk toolbox. Generate default by calling 'trunk-toolbox genconfig'

[ifchange]
enabled = true

[donotland]
enabled = true

[todo]
enabled = false

[neveredit]
enabled = true
paths = [""]   # paths to protect from modification
