# Configuration for trunk toolbox. Generate default by calling 'trunk-toolbox genconfig'

[ifchange]
enabled = false

[donotland]
enabled = false

[todo]
enabled = false

[neveredit]
enabled = true
paths = ["src/rules/mod.rs"]
