name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Cargo Test [linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Cargo Test
        run: cargo test

  trunk_check_runner:
    name: Trunk Check runner [linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Build trunk-toolbox
        run: cargo build

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.4
