name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Cargo Test [linux]
    runs-on: [self-hosted, ubuntu-x64]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Cargo Test
        run: cargo test -q --  -Z unstable-options --format json --report-time | /home/eli/.cargo/bin/cargo2junit > junit_report.xml

      - name: Upload results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: junit_report.xml
          org-slug: trunk-staging-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true

  trunk_check_runner:
    name: Trunk Check runner [linux]
    runs-on: [self-hosted, ubuntu-x64]

    steps:
      - uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: false
