name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk_check_runner:
    name: Trunk Check runner [linux]    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.2.0-alpha
