name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Cargo Test [linux]
    runs-on: [self-hosted, ubuntu-x64]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run tests
        run: cargo nextest run --profile=ci

      - name: Upload test results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: ${{ github.workspace }}/target/nextest/ci/*junit.xml
          org-slug: trunk
          token: ${{ secrets.TRUNK_PROD_ORG_API_TOKEN }}
        continue-on-error: true

  trunk_check_runner:
    name: Trunk Check runner [linux]
    runs-on: [self-hosted, ubuntu-x64]

    steps:
      - uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: false
