name: Release Horton CLI
on:
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      # TODO(sam): set up macos build
      - name: Set up toolchains
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build --release
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload to GitHub
        run: gh release upload GITHUB_TAG_GOES_HERE target/release/horton
