name: Release Horton CLI
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: Tag to create
concurrency: ${{ github.workflow }}

jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - target: x86_64-apple-darwin
            runs-on: macos-latest
          - target: aarch64-apple-darwin
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Set up toolchains
        run: rustup target add ${{ matrix.target }}

      - name: Build --release
        run: cargo build --release --target ${{ matrix.target }}
        env:
          HORTON_RELEASE: ${{ github.event.inputs.release_tag }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/trunk-toolbox

  tag_and_release:
    name: Tag and Release [ ${{ github.event.inputs.release_tag }} ]
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Compress binaries
        run:
          for target in x86_64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin
          do
            tar czvf trunk-toolbox-${target}.tar.gz -C artifacts/${target} trunk-toolbox
          done
          rm -rf artifacts

      - name: Create GH release and upload binary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --target ${{ github.ref }} ${{ github.event.inputs.release_tag }} --generate-notes
