name: Release Horton CLI
on:
  workflow_dispatch: {}
  pull_request: {}
concurrency: ${{ github.workflow }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      # TODO(sam): set up macos build
      - name: Set up toolchains
        run: rustup target add x86_64-unknown-linux-gnu

      # TODO(sam): cargo build --locked
      - name: Build --release
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload to GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -al . || true
          ls -al target/ || true
          ls -al target/debug/ || true
          ls -al target/release/ || true
          #gh release create 0.0.0-sam.0 --generate-notes
          gh release upload 0.0.0-sam.0 target/release/horton
